### ISSUE TITLE
https/secure SSL

### ISSUE THREAD

**Issue by loganesian411** [loganesian411/monte-christo-trade#11]
vimeo needs to be updated.

**Comment by 12wrigja** [comment]
That PR is only half the story - ideally, we should auto-redirect visitors of insecure pages to the secure versions. From [here](https://help.dreamhost.com/hc/en-us/articles/215747758-How-do-I-force-my-site-to-load-securely-with-an-htaccess-file-), I recommend the second option, which redirected everything including resources on the page (which should be automatic but might as well be sure).

To quote it here in case that link changes, the following goes in the .htaccess file for the site:
```
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301] 
````

I can do this if/when I get ssh access.
